# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c21c2339f44efdcd65efa44fcf031dafd6a0dadeabd44b9bc74ba847eb8498e55b4531b924bc07caa86be4001f597f5fc72973369044cad631b73f7274905ea

test:
  secret_key_base: b1c82a9db9cd6875f55a8c908ae8fb48d24770c464d51fdd831b3fd8afad529adea8ee44aa0c8d4536f21d4e3b61ed2ef5ae8fd936e795390fe01efff802b5ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
